### ISSUE TITLE
"Name"

### ISSUE THREAD

**Issue by Francis-Guerinat** [jackburton79/room#3]
Hello,
I use this room plugin on GLPI 10.0.2. All the data and reservations that existed on the version 9.5.7 of Glpi before its update are present.
The only problem is that I can't change the "NAME". 
![image](https://user-images.githubusercontent.com/111348503/184849609-c4e82f50-ab62-4690-b77c-c2f3ac283702.png)
Where can I correct this problem?

**Comment by FlorianV54** [comment]
Good Afternoon, 

We have the same issue with our GLPI 10.0.3 (we can't type text in "Name" field). Also in "Opening Times" etc..
And especially when you want to create a new room (I don't know if it's related to the fact that you can't put a name), when you click on "Add", no room is created.

Do you have an expected resolution date for this issue ?

**Comment by jackburton79** [comment]
Hi,
will have a look next week, probably

**Comment by jackburton79** [comment]
I accidentally broke this in a previous commit.

Fixed in 037e37ae6a372e637d0fb8fee76ccbf3a9b70df2
